Let applicationManager handle force close of applications
ubports/qtmir pull request #29
Opened 2019-08-22 18:04 UTC by mariogrip

If application (and not surface) is in the progress of closing, we
should let applicationManager (and upstart) handle closing and force
close (sigkill) of applications.

Fixes: https://github.com/ubports/ubuntu-touch/issues/1184

2019-08-23 14:08 UTC, dobey requested changes

2019-08-23 14:08 UTC, dobey commented on src/modules/Unity/Application/application.cpp
> +    // Se: https://github.com/ubports/ubuntu-app-launch/blob/9ffa5f76711d600c10c20795cdaeb2c0abfa7cde/libubuntu-app-launch/application-impl-base.cpp#L320
Se? See! :)

2019-08-23 14:09 UTC, mariogrip commented on src/modules/Unity/Application/application.cpp
> +    // Se: https://github.com/ubports/ubuntu-app-launch/blob/9ffa5f76711d600c10c20795cdaeb2c0abfa7cde/libubuntu-app-launch/application-impl-base.cpp#L320
Bad excuse: It's norwegian: https://www.babla.no/norsk-engelsk/se xD

2019-08-23 14:13 UTC, mariogrip commented
Plz Squash :)

2019-08-23 18:56 UTC, dobey approved these changes

2019-09-02 00:57 UTC, UniversalSuperBox approved these changes

2019-09-02 00:57 UTC, merged